; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = humiditymeter
name = DebugStand
description = Измеритель влажности почвы

[env]
custom_project_version = \"0.0.1\"
monitor_speed = 115200
build_flags = 
	-std=c++17

[env:humiditymeter]
framework = noneos-sdk
platform = ch32v
board = genericCH32V003F4P6
monitor_speed = 115200
build_flags = 
	-DVERSION=${env.custom_project_version}
	-D LOG_ENABLE
	-ffunction-sections
	-fdata-sections
	-Os
	-flto
build_src_filter = 
	-<*>
	+<main_ch32.cpp>
lib_deps = 
	https://github.com/AndyTakker/Logs.git
	https://github.com/AndyTakker/SysClock.git
	https://github.com/AndyTakker/ch32Pins.git
	; https://github.com/AndyTakker/TaskManager.git
	; https://github.com/AndyTakker/SettingsStore.git



[env:hu_meter_At85]
framework = arduino
platform = atmelavr
board = digispark-tiny
monitor_speed = 9600
build_flags = 
	-DVERSION=${env.custom_project_version}
	; -D ATtiny13
	-D LED_DISPLAY_ENABLED  ; Используеться LED-дисплей вместо светодиодов
	; -D LOG_ENABLE
	-ffunction-sections
	-fdata-sections
	-Os
	-flto
build_src_filter = 
	-<*>
	+<main_At85.cpp>

[env:hu_meter_At13]
framework = arduino
platform = atmelavr
board = attiny13
monitor_speed = 9600
build_flags = 
	-DVERSION=${env.custom_project_version}
	-D ATtiny13
	; -D LED_DISPLAY_ENABLED  ; Используеться LED-дисплей вместо светодиодов
	; -D LOG_ENABLE
	-ffunction-sections
	-fdata-sections
	-Os
	-flto
build_src_filter = 
	-<*>
	+<main_At85.cpp>
lib_ignore = 
	Soft_Serial